project_id: "terraform-demo-475117"
region: "us-central1"

gcs_bucket:
  name: "nishchya-yaml-dev-bucket-001"  # must be globally unique
  location: "US-CENTRAL1"
  versioning: true
  labels:
    environment: "dev"
    owner: "nishchya"
    managed_by: "terraform"
